use crate::{
    storage::{self, PoolInitMeta},
    PoolFactoryError,
};
use soroban_sdk::{
    contract, contractimpl, panic_with_error, Address, Bytes, BytesN, Env, IntoVal, String, Symbol,
};

use backstop::BackstopContract;
use pool::PoolContract;
use pool_factory::BackstopInit;

#[contract]
pub struct MockPoolFactory;

pub trait MockPoolFactoryTrait {
    /// Deploys and initializes a lending pool
    ///
    /// # Arguments
    /// * `admin` - The admin address for the pool
    /// * `name` - The name of the pool
    /// * `oracle` - The oracle address for the pool
    /// * `backstop_take_rate` - The backstop take rate for the pool (7 decimals)
    /// * `max_positions` - The maximum user positions supported by the pool
    /// * `min_collateral` - The minimum collateral required for a position
    /// * `backstop` - The backstop to deploy for the pool
    fn deploy(
        e: Env,
        admin: Address,
        name: String,
        salt: BytesN<32>,
        oracle: Address,
        backstop_take_rate: u32,
        max_positions: u32,
        min_collateral: i128,
        min_backstop: i128,
        backstop: BackstopInit,
        hook: Option<Address>,
    ) -> Address;

    /// Checks if contract address was deployed by the factory
    ///
    /// Returns true if pool was deployed by factory and false otherwise
    ///
    /// # Arguments
    /// * 'pool_address' - The contract address to be checked
    fn is_pool(e: Env, pool_address: Address) -> bool;

    /// Fetch the WASM hashes and the treasury every deployed pool is initialized with
    fn get_pool_init_meta(e: Env) -> PoolInitMeta;

    /// Mock Only: Set a pool_address as having been deployed by the pool factory
    ///
    /// ### Arguments
    /// * `pool_address` - The pool address to set
    fn set_pool(e: Env, pool_address: Address);
}

#[contractimpl]
impl MockPoolFactory {
    /// Construct the pool factory contract
    ///
    /// ### Arguments
    /// * `pool_init_meta` - The pool initialization metadata    
    pub fn __constructor(e: Env, pool_init_meta: PoolInitMeta) {
        storage::set_pool_init_meta(&e, &pool_init_meta);
    }
}

#[contractimpl]
impl MockPoolFactoryTrait for MockPoolFactory {
    fn deploy(
        e: Env,
        admin: Address,
        name: String,
        salt: BytesN<32>,
        oracle: Address,
        backstop_take_rate: u32,
        max_positions: u32,
        min_collateral: i128,
        min_backstop: i128,
        backstop: BackstopInit,
        hook: Option<Address>,
    ) -> Address {
        storage::extend_instance(&e);
        admin.require_auth();
        let pool_init_meta = storage::get_pool_init_meta(&e);

        // verify backstop take rate is within [0,1) with 9 decimals
        if backstop_take_rate >= 1_0000000 {
            panic_with_error!(&e, PoolFactoryError::InvalidPoolInitArgs);
        }

        // the backstop is bound to the pool's address, which is derived from the salt before the
        // pool is registered. Addresses are not generated inside this frame: the test PRNG is
        // seeded per invocation and would collide with addresses generated by the test itself.
        let pool_address = e
            .deployer()
            .with_current_contract(salt.clone())
            .deployed_address();
        let mut backstop_salt_as_bytes: Bytes = salt.into_val(&e);
        backstop_salt_as_bytes.extend_from_array(b"backstop");
        let backstop_salt = e.crypto().keccak256(&backstop_salt_as_bytes).to_bytes();
        let backstop_address = e
            .deployer()
            .with_current_contract(backstop_salt)
            .deployed_address();
        e.register_at(
            &backstop_address,
            BackstopContract {},
            (
                pool_address.clone(),
                backstop.backstop_token,
                pool_init_meta.treasury,
                backstop.decimals_offset,
                backstop.name,
                backstop.symbol,
                hook.clone(),
            ),
        );
        e.register_at(
            &pool_address,
            PoolContract {},
            (
                admin,
                name,
                oracle,
                backstop_take_rate,
                max_positions,
                min_collateral,
                min_backstop,
                backstop_address.clone(),
                hook.clone(),
            ),
        );

        storage::set_deployed(&e, &pool_address);

        e.events().publish(
            (Symbol::new(&e, "deploy"),),
            (pool_address.clone(), backstop_address, hook),
        );
        pool_address
    }

    fn is_pool(e: Env, pool_address: Address) -> bool {
        storage::is_deployed(&e, &pool_address)
    }

    fn get_pool_init_meta(e: Env) -> PoolInitMeta {
        storage::get_pool_init_meta(&e)
    }

    fn set_pool(e: Env, pool_address: Address) {
        storage::set_deployed(&e, &pool_address);
    }
}
